/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
         this.setLocationRelativeTo(null);
           setSize(1190, 860);
         setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSalir1 = new javax.swing.JButton();
        lblBienvenidos = new javax.swing.JLabel();
        jButtonInstrucciones = new javax.swing.JButton();
        ButtonJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ButtonSalir1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSalir1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 36)); // NOI18N
        ButtonSalir1.setForeground(new java.awt.Color(0, 255, 0));
        ButtonSalir1.setText("3. SALIR DEL JUEGO");
        ButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSalir1);
        ButtonSalir1.setBounds(50, 480, 520, 130);

        lblBienvenidos.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        lblBienvenidos.setForeground(new java.awt.Color(0, 255, 0));
        lblBienvenidos.setText("! Bienvenido al juego de batalla \"FEROVA\" game !");
        lblBienvenidos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBienvenidos);
        lblBienvenidos.setBounds(50, 690, 1030, 45);

        jButtonInstrucciones.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInstrucciones.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 36)); // NOI18N
        jButtonInstrucciones.setForeground(new java.awt.Color(51, 255, 51));
        jButtonInstrucciones.setText("2. INSTRUCCIONES");
        getContentPane().add(jButtonInstrucciones);
        jButtonInstrucciones.setBounds(50, 320, 520, 130);

        ButtonJugar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonJugar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 48)); // NOI18N
        ButtonJugar.setForeground(new java.awt.Color(51, 255, 0));
        ButtonJugar.setText("1. JUGAR");
        ButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonJugar);
        ButtonJugar.setBounds(70, 100, 480, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1270, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJugarActionPerformed
        // TODO add your handling code here:
        
        Iniciar entrada1 = new Iniciar();
        entrada1.show();
        entrada1.setSize(825, 866);
        dispose();
        
        /*  Juego j = new Juego();
        }j.setSize(1190, 770);
        j.setLocation(5,5);

        panelPrincipal.removeAll();
        panelPrincipal.add(j, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();*/
    }//GEN-LAST:event_ButtonJugarActionPerformed

    private void ButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonJugar;
    private javax.swing.JButton ButtonSalir1;
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenidos;
    // End of variables declaration//GEN-END:variables
}
