/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class Comprar extends javax.swing.JFrame {

    /**
     * Creates new form Comprar
     */
    public Comprar() {
        initComponents();
        this.setLocationRelativeTo(null);
           setSize(1290, 900);
           setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButtonrTienda = new javax.swing.JButton();
        jButtonComprarBoots = new javax.swing.JButton();
        jButtonComprarV = new javax.swing.JButton();
        jButtonComprarArmas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("COMPRAR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 50, 470, 40);

        jButtonrTienda.setBackground(new java.awt.Color(255, 255, 255));
        jButtonrTienda.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonrTienda.setForeground(new java.awt.Color(0, 255, 0));
        jButtonrTienda.setText("Regresar");
        jButtonrTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonrTienda);
        jButtonrTienda.setBounds(40, 620, 260, 100);

        jButtonComprarBoots.setBackground(new java.awt.Color(255, 255, 255));
        jButtonComprarBoots.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonComprarBoots.setForeground(new java.awt.Color(0, 255, 0));
        jButtonComprarBoots.setText("BOOTS");
        jButtonComprarBoots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarBootsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprarBoots);
        jButtonComprarBoots.setBounds(100, 450, 450, 120);

        jButtonComprarV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonComprarV.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonComprarV.setForeground(new java.awt.Color(0, 255, 0));
        jButtonComprarV.setText("COMPRAR VEHÍCULOS");
        jButtonComprarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarVActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprarV);
        jButtonComprarV.setBounds(50, 310, 560, 120);

        jButtonComprarArmas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonComprarArmas.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonComprarArmas.setForeground(new java.awt.Color(0, 255, 0));
        jButtonComprarArmas.setText("COMPRAR ARMAS");
        jButtonComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarArmasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprarArmas);
        jButtonComprarArmas.setBounds(110, 170, 450, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarArmasActionPerformed
        // TODO add your handling code here:
        JuegoTableros entrada2 = new JuegoTableros();
        entrada2.show();
        entrada2.setSize(1290, 1000);
        dispose();

     
    }//GEN-LAST:event_jButtonComprarArmasActionPerformed

    private void jButtonComprarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprarVActionPerformed

    private void jButtonComprarBootsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarBootsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprarBootsActionPerformed

    private void jButtonrTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrTiendaActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);

        new Tienda ().setVisible(true);

        setSize(1290, 1000);
        dispose();
       
    }//GEN-LAST:event_jButtonrTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprarArmas;
    private javax.swing.JButton jButtonComprarBoots;
    private javax.swing.JButton jButtonComprarV;
    private javax.swing.JButton jButtonrTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
