/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import java.util.LinkedList;

/**
 *
 * @author danie
 */
public class CrearArmas extends javax.swing.JFrame {
 public static LinkedList contenedor = new LinkedList();
    public int buscar;
    /**
     * Constructor de mi JFRAME CrearArmas
     * Creates new form CrearArmas
     */
    public CrearArmas() {
        initComponents();
           this.setLocationRelativeTo(null);
           setSize(1290, 1000);
           setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonRegresarTipos = new javax.swing.JButton();
        jButtonGuardarArma = new javax.swing.JButton();
        jTextFieldV1 = new javax.swing.JTextField();
        jTextFieldV2 = new javax.swing.JTextField();
        jTextFieldV3 = new javax.swing.JTextField();
        jTextFieldV4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COSTO DEL ARMA:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 540, 420, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Creación de Armas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 80, 450, 100);

        jButtonRegresarTipos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarTipos.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarTipos.setForeground(new java.awt.Color(0, 255, 0));
        jButtonRegresarTipos.setText("Regresar");
        jButtonRegresarTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarTiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarTipos);
        jButtonRegresarTipos.setBounds(60, 680, 260, 100);

        jButtonGuardarArma.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarArma.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonGuardarArma.setForeground(new java.awt.Color(0, 255, 0));
        jButtonGuardarArma.setText("Guardar arma ");
        jButtonGuardarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarArmaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarArma);
        jButtonGuardarArma.setBounds(490, 680, 510, 110);

        jTextFieldV1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV1.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV1);
        jTextFieldV1.setBounds(480, 300, 310, 40);

        jTextFieldV2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV2.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV2);
        jTextFieldV2.setBounds(480, 370, 310, 40);

        jTextFieldV3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV3.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV3.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV3);
        jTextFieldV3.setBounds(480, 450, 310, 40);

        jTextFieldV4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV4.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV4.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV4);
        jTextFieldV4.setBounds(480, 540, 310, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese puntería:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 450, 420, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese ataque:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 370, 420, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese nombre del arma:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 300, 420, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/arma.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 30, 560, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV1ActionPerformed

    private void jTextFieldV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV2ActionPerformed

    private void jTextFieldV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV3ActionPerformed

    private void jTextFieldV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV4ActionPerformed
/**
 * Método para guardar arma creada
 * @param evt 
 */
    private void jButtonGuardarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarArmaActionPerformed
        // TODO add your handling code here:
        JuegoTableros entrada2 = new JuegoTableros();
        entrada2.show();
        entrada2.setSize(1290, 1000);
        dispose();

        /*Sring nombre = jTextFieldNombre.getText();
        String v1 = jTextFieldV1.getText();
        String v2 = jTextFieldV2.getText();
        String v3 = jTextFieldV3.getText();
        String tipo1 = Jmostrar1.getText();
        String tipo2 = Jmostrar2.getText();
        String tipo3 = Jmostrar3.getText();
        //NOMBRE DE LA PERSONA ATRUBUTOS
        Persona  person = new Persona(nombre, v1, v2, v3, tipo1, tipo2, tipo3);
        contenedor.add(person);
        //Limpia
        jTextFieldNombre.setText("");
        jTextFieldV1.setText("");
        jTextFieldV2.setText("");
        jTextFieldV3.setText("");*/
    }//GEN-LAST:event_jButtonGuardarArmaActionPerformed
/**
 * Botón para regresar a mi JFRAME Tienda
 * @param evt 
 */
    private void jButtonRegresarTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarTiposActionPerformed
        // TODO add your handling code here:
        //Persona persona = new Persona(jTextFieldNombre.getText() );
        //lista.add(persona);
        this.setVisible(false);

        new Tienda().setVisible(true);

         setSize(825, 866);
          dispose();
        /*  String nombre = jTextFieldNombre.getText();
        String v1 = jTextFieldV1.getText();
        String v2 = jTextFieldV2.getText();
        String v3 = jTextFieldV3.getText();
        String tipo1 = Jmostrar1.getText();
        String tipo2 = Jmostrar2.getText();
        String tipo3 = Jmostrar3.getText();
        //NOMBRE DE LA PERSONA ATRUBUTOS
        Persona  person = new Persona(nombre, v1, v2, v3, tipo1, tipo2, tipo3);
        contenedor.add(person);
        //Limpia
        jTextFieldNombre.setText("");
        jTextFieldV1.setText("");
        jTextFieldV2.setText("");
        jTextFieldV3.setText("");*/
    }//GEN-LAST:event_jButtonRegresarTiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearArmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarArma;
    private javax.swing.JButton jButtonRegresarTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldV1;
    private javax.swing.JTextField jTextFieldV2;
    private javax.swing.JTextField jTextFieldV3;
    private javax.swing.JTextField jTextFieldV4;
    // End of variables declaration//GEN-END:variables
}
