/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.Persona;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Estadisticas extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;
    int cont = 0;
    

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
        CargarRegistrar();
        Cargardatos();
    }
public void CargarRegistrar(){
    String datos [][]= {};
    String columna[]= {"Nombre"};
    modelo= new DefaultTableModel(datos, columna);
    jTableEstadisticas.setModel(modelo);
    
}
            public void Cargardatos(){
                Persona a;
                for (int i = 0; i < Registrar.contenedor.size(); i++) {
                    a= (Persona)Registrar.contenedor.get(i);
                    modelo.insertRow(cont, new Object []{ });
                    modelo.setValueAt(a.getNombre(), cont, 0);
                    
                    
                }
                    
                
                
            }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadisticas = new javax.swing.JTable();
        jButtonRegresarE = new javax.swing.JButton();
        jButtonSalirE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableEstadisticas.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 14)); // NOI18N
        jTableEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Vehículo 1", "Vehículo 2", "Vehículo 3"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadisticas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 840, 610);

        jButtonRegresarE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarE.setForeground(new java.awt.Color(0, 255, 51));
        jButtonRegresarE.setText("Regresar");
        jButtonRegresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarE);
        jButtonRegresarE.setBounds(90, 900, 240, 100);

        jButtonSalirE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonSalirE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirE.setText("Salir del Juego");
        jButtonSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirE);
        jButtonSalirE.setBounds(930, 900, 270, 110);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Datos del juego");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 60, 210, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         
        new OpcionesFinales().setVisible(true);
        setSize(825, 866);
          dispose();
    }//GEN-LAST:event_jButtonRegresarEActionPerformed

    private void jButtonSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresarE;
    private javax.swing.JButton jButtonSalirE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadisticas;
    // End of variables declaration//GEN-END:variables
}
