/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.Persona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Estadisticas extends javax.swing.JFrame {
   
    private DefaultTableModel modelo;
    int cont = 0;


    /**
     * Constructor de mi JFRAME Estadisticas
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
         this.setLocationRelativeTo(null);
        setSize(1490, 1200);
        setTitle("FEROVA GAME");
        CargarRegistrar();
        Cargardatos();
    }
    /**
     * Método para colocoar en mi JTABLE
     */
public void CargarRegistrar(){
    String datos [][]= {};
    String columna[]= {"Nombre", "Nombre Vehículo1", "Tipo", "Nombre Vehículo2","Tipo","Nombre Vehículo3", "Tipo"};
    String columna1[] = { "V1" };
    
    
        
  
    
    modelo= new DefaultTableModel(datos, columna);
    jTableEstadisticas.setModel(modelo);
    
}
              /**
               * Método para cargar los datos de mi clase persona y mi JFRAME registrar
               */
            public void Cargardatos(){
                Persona a;
                Registrar b;
                for (int i = 0; i < Registrar.contenedor.size(); i++) {
                    a= (Persona)Registrar.contenedor.get(i);
                  //  b= (Registrar) Registrar.contenedor.get(i);
                    modelo.insertRow(cont, new Object []{ });
                    modelo.setValueAt(a.getNombre(), cont, 0);
                    modelo.setValueAt(a.getV1(), cont, 1);
                    modelo.setValueAt(a.getV2(), cont, 3);
                    modelo.setValueAt(a.getV3(), cont, 5);
                     modelo.setValueAt(a.getTipo1(), cont, 2);
                     modelo.setValueAt(a.getTipo2(), cont, 4);
                     modelo.setValueAt(a.getTipo3(), cont, 6);
                     
                    
                    
                    
                }
                    
                
                
            }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNuevo = new javax.swing.JLabel();
        JBBorrar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadisticas = new javax.swing.JTable();
        jButtonRegresarE = new javax.swing.JButton();
        jButtonSalirE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNuevo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevo.setText("jLabel3");
        getContentPane().add(jLabelNuevo);
        jLabelNuevo.setBounds(410, 90, 300, 60);

        JBBorrar.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        JBBorrar.setForeground(new java.awt.Color(0, 0, 0));
        JBBorrar.setText("Borrar");
        JBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBBorrar);
        JBBorrar.setBounds(730, 870, 124, 40);

        jBActualizar.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jBActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBActualizar);
        jBActualizar.setBounds(520, 870, 170, 40);

        jTableEstadisticas.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        jTableEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nombre V1", "Tipo de Vehículo1", "Nombre V2", "TIpo de Vehículo2", "Nombre V3", "Tipo de Vehículo3"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadisticas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 1170, 550);

        jButtonRegresarE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarE.setForeground(new java.awt.Color(0, 255, 51));
        jButtonRegresarE.setText("Regresar");
        jButtonRegresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarE);
        jButtonRegresarE.setBounds(90, 900, 240, 100);

        jButtonSalirE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonSalirE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirE.setText("Salir del Juego");
        jButtonSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirE);
        jButtonSalirE.setBounds(930, 900, 270, 110);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Datos del juego");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 20, 210, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 1310);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para regresar a mi JFRAME OpcionesFinales 
 * @param evt 
 */
    private void jButtonRegresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         
        new OpcionesFinales().setVisible(true);
        setSize(825, 866);
          dispose();
    }//GEN-LAST:event_jButtonRegresarEActionPerformed
/**
 * Método para salir del juego
 * @param evt 
 */
    private void jButtonSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEActionPerformed

    private void JBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBorrarActionPerformed

        if(jTableEstadisticas.getSelectedRow()==-1){
            if(jTableEstadisticas.getRowCount()<=0){
                jLabelNuevo.setText("No hay datos todavía en la tabla");
            }else{
                jLabelNuevo.setText("Seleccione primero una fila o un dato");
            }
        }else{
            if(JOptionPane.showConfirmDialog(null,"¿seguro que lo quieres eliminar?")==0){
                DefaultTableModel model = (DefaultTableModel) jTableEstadisticas.getModel();
                model.removeRow(jTableEstadisticas.getSelectedRow());
            }
        }
    }//GEN-LAST:event_JBBorrarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        if(jTableEstadisticas.getSelectedRow()==-1){
            if(jTableEstadisticas.getRowCount()<=0){
                jLabelNuevo.setText("No hay información en la tabla");
            }else{
                jLabelNuevo.setText("Seleccione primero una fila o un dato");
            }
        }else{
            DefaultTableModel model = (DefaultTableModel) jTableEstadisticas.getModel();
            //modelo.setValueAt(this.jtxtNombre.getText(), jTableEstadisticas.getSelectedRow(), 0);
           // modelo.setValueAt(this.jtxtPunteo.getText(), jTableEstadisticas.getSelectedRow(), 1);
           // modelo.setValueAt(this.jtxtFecha.getText(), jTableEstadisticas.getSelectedRow(), 2);
        }
    }//GEN-LAST:event_jBActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBorrar;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jButtonRegresarE;
    private javax.swing.JButton jButtonSalirE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadisticas;
    // End of variables declaration//GEN-END:variables
}
