/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class Iniciar extends javax.swing.JFrame {

    /**
     * Constructor de mi JFRAME Iniciar
     * Creates new form Iniciar
     */
    public Iniciar() {
        initComponents();
        this.setLocationRelativeTo(null);
 setSize(825, 866);
        setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonTienda1 = new javax.swing.JButton();
        jButtonRBienvenido = new javax.swing.JButton();
        jButtonSiguiente2 = new javax.swing.JButton();
        jButtonTienda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonTienda1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTienda1.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonTienda1.setForeground(new java.awt.Color(255, 0, 51));
        jButtonTienda1.setText("Cargar una partida");
        jButtonTienda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTienda1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTienda1);
        jButtonTienda1.setBounds(240, 350, 360, 110);

        jButtonRBienvenido.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRBienvenido.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 18)); // NOI18N
        jButtonRBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRBienvenido.setText("Regresar");
        jButtonRBienvenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRBienvenidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRBienvenido);
        jButtonRBienvenido.setBounds(40, 730, 160, 50);

        jButtonSiguiente2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSiguiente2.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jButtonSiguiente2.setForeground(new java.awt.Color(255, 0, 51));
        jButtonSiguiente2.setText("ir a jugar");
        jButtonSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguiente2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente2);
        jButtonSiguiente2.setBounds(260, 200, 340, 110);

        jButtonTienda.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTienda.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonTienda.setForeground(new java.awt.Color(255, 0, 51));
        jButtonTienda.setText("Tienda");
        jButtonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTienda);
        jButtonTienda.setBounds(290, 490, 250, 140);

        jLabel3.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Seleccione una opción");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 20, 500, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/Nacis.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 800);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 60, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para regresar al Bienvenido
 * @param evt 
 */
    private void jButtonRBienvenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRBienvenidoActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         
        new Bienvenido().setVisible(true);
        setSize(1190, 860);
          dispose();
       
    }//GEN-LAST:event_jButtonRBienvenidoActionPerformed
/**
 * Método para ir JFRAME tienda
 * @param evt 
 */
    private void jButtonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiendaActionPerformed
        // TODO add your handling code here:
        Tienda entrada4 = new Tienda();
        entrada4.show();
        entrada4.setSize(825, 866);
        dispose();
    }//GEN-LAST:event_jButtonTiendaActionPerformed
/**
 * Método para ir a JFRAME OpcionesJuego
 * @param evt 
 */
    private void jButtonSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguiente2ActionPerformed
        // TODO add your handling code here:
       OpcionesJuego opcion = new OpcionesJuego();
       opcion.show();
       opcion.setSize(825, 866);
       dispose();
    }//GEN-LAST:event_jButtonSiguiente2ActionPerformed

    private void jButtonTienda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTienda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTienda1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRBienvenido;
    private javax.swing.JButton jButtonSiguiente2;
    private javax.swing.JButton jButtonTienda;
    private javax.swing.JButton jButtonTienda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
