/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class OpcionesJuego extends javax.swing.JFrame {

    /**
     * Constructor de mi JFRAME OpcionesJuego
     * Creates new form OpcionesJuego
     */
    public OpcionesJuego() {
        initComponents();
            this.setLocationRelativeTo(null);
 setSize(825, 866);
        setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonSalirOP = new javax.swing.JButton();
        jButtonJJ = new javax.swing.JButton();
        jButtonRTienda = new javax.swing.JButton();
        jButtonJC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Seleccione alguna opción");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 10, 410, 70);

        jButtonSalirOP.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalirOP.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jButtonSalirOP.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSalirOP.setText("Salir");
        jButtonSalirOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirOPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirOP);
        jButtonSalirOP.setBounds(510, 660, 250, 90);

        jButtonJJ.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJJ.setFont(new java.awt.Font("Haettenschweiler", 3, 24)); // NOI18N
        jButtonJJ.setForeground(new java.awt.Color(255, 0, 0));
        jButtonJJ.setText("JUGADOR VS JUGADOR");
        jButtonJJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJJ);
        jButtonJJ.setBounds(240, 330, 350, 120);

        jButtonRTienda.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRTienda.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jButtonRTienda.setForeground(new java.awt.Color(255, 0, 0));
        jButtonRTienda.setText("Regresar");
        jButtonRTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRTienda);
        jButtonRTienda.setBounds(50, 660, 250, 90);

        jButtonJC.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJC.setFont(new java.awt.Font("Haettenschweiler", 3, 24)); // NOI18N
        jButtonJC.setForeground(new java.awt.Color(255, 0, 0));
        jButtonJC.setText("JUGADOR VS COMPUTADORA");
        jButtonJC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJC);
        jButtonJC.setBounds(230, 150, 350, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/Nacis.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para regresar a mi JFRAME tienda
 * @param evt 
 */
    private void jButtonRTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRTiendaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        new Iniciar().setVisible(true);
        setSize(825, 866);
        dispose();
    }//GEN-LAST:event_jButtonRTiendaActionPerformed
/**
 * Botón salir
 * @param evt 
 */
    private void jButtonSalirOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirOPActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jButtonSalirOPActionPerformed
/**
 * Método para ir a Registrar Usuario y elegir sus tres vehículos de Jugador vs Computadora
 * @param evt 
 */
    private void jButtonJCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJCActionPerformed
        // TODO add your handling code here:
          Registrar entrada2 = new Registrar();
        entrada2.show();
        entrada2.setSize(1290, 1000);
        dispose();
    }//GEN-LAST:event_jButtonJCActionPerformed
/**
 * Método para ir a Regsitrar a los dos usuarios y los 6 vehículos de JUGADOR VS JUGADOR
 * @param evt 
 */
    private void jButtonJJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJJActionPerformed
        // TODO add your handling code here:
          JuegoTableros entrada2 = new JuegoTableros();
        entrada2.show();
        entrada2.setSize(1290, 1000);
        dispose();
    }//GEN-LAST:event_jButtonJJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJC;
    private javax.swing.JButton jButtonJJ;
    private javax.swing.JButton jButtonRTienda;
    private javax.swing.JButton jButtonSalirOP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
