/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class OpcionesFinales extends javax.swing.JFrame {

    /**
     * Constructor de JFRAME de OpcionesFinales
     * Creates new form Estadisticas
     */
    public OpcionesFinales() {
        initComponents();
          this.setLocationRelativeTo(null);
          setSize(825, 866);
        setTitle("FEROVA GAME");
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalirFinal = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonGuardarJuego = new javax.swing.JButton();
        jButtonNuevoJuego = new javax.swing.JButton();
        jButtonEstadisticas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSalirFinal.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalirFinal.setFont(new java.awt.Font("Dubai Medium", 3, 36)); // NOI18N
        jButtonSalirFinal.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirFinal.setText("Salir del juego");
        jButtonSalirFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirFinal);
        jButtonSalirFinal.setBounds(480, 700, 280, 70);

        jButtonReportes.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReportes.setFont(new java.awt.Font("Dubai Medium", 3, 36)); // NOI18N
        jButtonReportes.setForeground(new java.awt.Color(255, 0, 0));
        jButtonReportes.setText("Reportes");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReportes);
        jButtonReportes.setBounds(190, 200, 420, 80);

        jButtonGuardarJuego.setBackground(new java.awt.Color(0, 0, 0));
        jButtonGuardarJuego.setFont(new java.awt.Font("Dubai Medium", 3, 36)); // NOI18N
        jButtonGuardarJuego.setForeground(new java.awt.Color(255, 0, 0));
        jButtonGuardarJuego.setText("Guardar Juego");
        jButtonGuardarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarJuego);
        jButtonGuardarJuego.setBounds(200, 420, 420, 80);

        jButtonNuevoJuego.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNuevoJuego.setFont(new java.awt.Font("Dubai Medium", 3, 36)); // NOI18N
        jButtonNuevoJuego.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNuevoJuego.setText("Jugar de nuevo");
        jButtonNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoJuego);
        jButtonNuevoJuego.setBounds(200, 310, 420, 80);

        jButtonEstadisticas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEstadisticas.setFont(new java.awt.Font("Dubai Medium", 3, 36)); // NOI18N
        jButtonEstadisticas.setForeground(new java.awt.Color(255, 0, 0));
        jButtonEstadisticas.setText("Estadísticas del Juego");
        jButtonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEstadisticas);
        jButtonEstadisticas.setBounds(180, 90, 440, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/Nacis.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para ir a mi JFRAME Iniciar
 * @param evt 
 */
    private void jButtonNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoJuegoActionPerformed
        // TODO add your handling code here:
        Iniciar nuevo = new Iniciar();
        nuevo.show();
        nuevo.setSize(825, 866);
        dispose();
    }//GEN-LAST:event_jButtonNuevoJuegoActionPerformed
/**
 * Método para ir a Guardar partida
 * @param evt 
 */
    private void jButtonGuardarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarJuegoActionPerformed
/**
 * Método para ir JFRAME reportes
 * @param evt 
 */
    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed
/**
 * Método para salir del juego
 * @param evt 
 */
    private void jButtonSalirFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirFinalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirFinalActionPerformed
/**
 * Método para ir a mi JFRAME Estadística 
 * @param evt 
 */
    private void jButtonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadisticasActionPerformed
        // TODO add your handling code here:
      /*  Estadisticas e = new Estadisticas();
        e.show();
        e.setSize(1490, 1200);
        dispose();*/
      this.setVisible(false);
      new Estadisticas().setVisible(true);
      
    }//GEN-LAST:event_jButtonEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesFinales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstadisticas;
    private javax.swing.JButton jButtonGuardarJuego;
    private javax.swing.JButton jButtonNuevoJuego;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonSalirFinal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
