/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.Persona;
import java.util.ArrayList;
import java.util.LinkedList;

/**
 *
 * @author danie
 */
public class Registrar extends javax.swing.JFrame {
  //  ArrayList<Persona> lista = new ArrayList<Persona>();
    public static LinkedList contenedor = new LinkedList();
    public int buscar;
    
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
         this.setLocationRelativeTo(null);
         setSize(1290, 1000);
        setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxV1 = new javax.swing.JComboBox<>();
        jButtonIR = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBoxV1.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        jComboBoxV1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avion", "Tanque", " " }));
        getContentPane().add(jComboBoxV1);
        jComboBoxV1.setBounds(420, 160, 160, 42);

        jButtonIR.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIR.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonIR.setForeground(new java.awt.Color(255, 0, 0));
        jButtonIR.setText("Ir a Jugar");
        jButtonIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIR);
        jButtonIR.setBounds(930, 160, 220, 80);

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar);
        jButtonRegistrar.setBounds(920, 50, 220, 80);

        jLabel3.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Seleccione Vehículo 1:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 380, 50);

        jLabel4.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Ingrese su nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 50, 310, 62);

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(370, 60, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        //Persona persona = new Persona(jTextFieldNombre.getText() );
        //lista.add(persona);
        
        String nombre = jTextFieldNombre.getText();
        
        //NOMBRE DE LA PERSONA ATRUBUTOS
        Persona  person = new Persona(nombre);
        contenedor.add(person);
        //
        jTextFieldNombre.setText("");
        
        
      //  mostrar();
        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIRActionPerformed
        // TODO add your handling code here:
        JuegoTableros entrada2 = new JuegoTableros();
        entrada2.show();
        entrada2.setSize(1290, 1000);
        dispose();
    }//GEN-LAST:event_jButtonIRActionPerformed
 
 /*   public void mostrar(){
        String matriz[][] = new String [lista.size()] [4];
        for (int i = 0; i < lista.size(); i++) {
            matriz [i][0]= lista.get(i).getNombre();
            
            
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIR;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxV1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
