/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

/**
 *
 * @author danie
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
        this.setLocationRelativeTo(null);

        setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrearA = new javax.swing.JButton();
        jButtonCrearV = new javax.swing.JButton();
        jButtonRTienda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Crear Armas");
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 590, 250, 90);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Seleccione alguna opción");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 10, 410, 70);

        jButtonCrearA.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCrearA.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jButtonCrearA.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCrearA.setText("Crear Armas");
        getContentPane().add(jButtonCrearA);
        jButtonCrearA.setBounds(280, 280, 250, 90);

        jButtonCrearV.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCrearV.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jButtonCrearV.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCrearV.setText("Crear Vehículos");
        getContentPane().add(jButtonCrearV);
        jButtonCrearV.setBounds(280, 170, 250, 90);

        jButtonRTienda.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRTienda.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jButtonRTienda.setForeground(new java.awt.Color(255, 0, 0));
        jButtonRTienda.setText("Regresar");
        jButtonRTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRTienda);
        jButtonRTienda.setBounds(50, 580, 250, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/Nacis.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRTiendaActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         
        new Iniciar().setVisible(true);
        setSize(825, 866);
          dispose();
    }//GEN-LAST:event_jButtonRTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCrearA;
    private javax.swing.JButton jButtonCrearV;
    private javax.swing.JButton jButtonRTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
